---
version: '3'

services:
  app:
    stdin_open: true
    build: .
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    ports: 
      - 3000:3000
    depends_on:
      - db
    command: rails s -b '0.0.0.0'
    
  db:
    image: postgres:14.1-alpine
    restart: always
    expose:
      - 5432
    env_file:
      - .env
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
